### ISSUE TITLE
question

### ISSUE THREAD

**Issue by saeternes** [CaptainTwin/Hackersbot#1]
do we do it from top to bottom to type it into vs code?

**Comment by Boxck** [comment]
@DevCassie

**Comment by DevCassie** [comment]
> do we do it from top to bottom to type it into vs code? 

Nah, you can clone the repository

**Comment by Boxck** [comment]
ok

**Comment by Nicaperson** [comment]
> > do we do it from top to bottom to type it into vs code?
> 
> Nah, you can clone the repository

how?

**Comment by Boxck** [comment]
the README.md can i just have it there or should i delete it?

**Comment by Boxck** [comment]
is it possible that i can add that code into another code of a bot or do i have to make a new bot?

**Comment by Boxck** [comment]
@DevCassie

**Comment by DevCassie** [comment]
> is it possible that i can add that code into another code of a bot or do i have to make a new bot?

Most likely you would need to rewrite a bit of the code for multiple reasons.

1. It's outdated.
2. It's most likely a different setup then yours.

But you can use this as a reference yeah of course.

**Comment by DevCassie** [comment]
> the README.md can i just have it there or should i delete it?

A readme file contains information about the project

**Comment by Boxck** [comment]
ok

**Comment by Boxck** [comment]
when i try to lanuch the bot it says that discord is already declared did you get the bot online? i made a new bot for this thing

**Comment by DevCassie** [comment]
> when i try to lanuch the bot it says that discord is already declared did you get the bot online? i made a new bot for this thing

When it was created created firstly, yes it could go online. However the code is outdated so that could be a reason. And depending if you just copied everything and pasted everything on your already existing code, it doesn't work that way.
